import fs from "node:fs";
import path from "node:path";
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const root = process.cwd();
const layout = fs.readFileSync(path.join(root, "sandbox/probe-lab/cinematic-production/ui/cinematic-production-runtime-layout.ts"), "utf8");
const runtime = fs.readFileSync(path.join(root, "sandbox/probe-lab/cinematic-production/ui/cinematic-production-runtime-canvas.tsx"), "utf8");
for (const marker of ["supportTransitionForInsert", "recapPulse", "animalCameraFocus", "fishFocus", "appleRecap", "burgerRecap", "nigiriRecap", "finalEmphasis"]) assert(layout.includes(marker), `CP.1E.5 layout is missing shot-rhythm marker: ${marker}`);
const fishLegacy = (layout.includes("lerp(1, 0.04, burgerDeemphasis)") || layout.includes("burgerDeemphasis - 0.72")) && layout.includes("{ position: [0.2, 1.62, 3.18]");
const fishCp1e7 = layout.includes("lerp(0.98, 0.82, burgerDeemphasis)") && layout.includes("lerp(1, 0.72") && layout.includes("MASTER_CAMERA_KEYS");
const fishParallaxSuccessor = layout.includes("sampleContinuousInsertJourney") && layout.includes("Foreground anchor: keep the burger physical, opaque, and nearly stationary.") && layout.includes("real back-plane position") && layout.includes("fishFocus");
assert(fishLegacy || fishCp1e7 || fishParallaxSuccessor, "CP.1E.5-family runtime must preserve a dedicated goldfish focus beat with burger context and fish emphasis.");
assert((layout.match(/animalCameraFocus/g) ?? []).length >= 4 && (layout.includes("fov: 30.2") || layout.includes("fov: 31.6") || layout.includes("MASTER_CAMERA_KEYS")), "CP.1E.5-family cow/chicken beats must preserve restrained camera focus behavior.");
const legacySupport = (layout.includes("xOffset: side * 0.18 * shaped") || layout.includes("xOffset: side * 0.22 * movement")) && (layout.includes("zOffset: 0.11 * shaped") || layout.includes("zOffset: 0.14 * movement"));
const stagingSuccessor = layout.includes("staging-first de-emphasis") && layout.includes("xOffset: side * 0.34 * movement") && layout.includes("zOffset: 0.22 * movement");
const persistentJourneySupport = layout.includes("galleryFoods") && layout.includes("sampleContinuousInsertJourney");
assert(legacySupport || stagingSuccessor || persistentJourneySupport, "CP.1E.5-family runtime must retain support-food clearing/staging through physical motion.");
assert(layout.includes("recapPulse(progress, 0.16") && layout.includes("recapPulse(progress, 0.37") && layout.includes("recapPulse(progress, 0.58"), "CP.1E.5 return-to-tray recap beats must remain available.");
assert(/function sampleReturnTray[\s\S]*?hand: hiddenActor\(\),/.test(layout) && /function sampleHero[\s\S]*?hand: hiddenActor\(\),/.test(layout), "CP.1E.5 must keep the hand out of the ending sequence.");
assert(runtime.includes("protectCameraFraming") && runtime.includes("applyGroupEmphasis") && runtime.includes('frameloop="demand"') && runtime.includes('powerPreference: "low-power"'), "CP.1E.5 must preserve safe framing, outline emphasis, and low-overhead runtime behavior.");
console.log("Cinematic Production CP.1E.5-family shot-rhythm verification passed.");
