import fs from "node:fs";
import path from "node:path";
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const root = process.cwd();
const layout = fs.readFileSync(path.join(root, "sandbox/probe-lab/cinematic-production/ui/cinematic-production-runtime-layout.ts"), "utf8");
const runtime = fs.readFileSync(path.join(root, "sandbox/probe-lab/cinematic-production/ui/cinematic-production-runtime-canvas.tsx"), "utf8");
const hasLegacyBoundaryCamera = ["hermiteScalar", "hermiteVec3", "cameraVelocityAtRawTime", "continuousCameraAtTime", "blendWindowS = 0.34"].every((marker) => layout.includes(marker));
const hasCp1e7MasterCamera = layout.includes("MASTER_CAMERA_KEYS") && layout.includes("masterCameraAtTime") && layout.includes("catmullRomVec3");
const hasThroughMotionMasterCamera = layout.includes("MASTER_CAMERA_KEYS") && layout.includes("masterCameraAtTime") && layout.includes("masterCameraVec3TangentAt") && layout.includes("hermiteVec3");
assert(layout.includes("sampleRawCinematicBurgerRuntime") && (hasLegacyBoundaryCamera || hasCp1e7MasterCamera || hasThroughMotionMasterCamera), "CP.1E.6-family runtime must retain continuous camera choreography.");
const legacyMovementLedSupport = (layout.includes("Movement leads the transition") || layout.includes("staging-first de-emphasis")) && layout.includes("fadeTail") && layout.includes("xOffset: side *");
const persistentJourneySupport = layout.includes("sampleContinuousInsertJourney") && layout.includes("galleryFoods") && layout.includes("Foreground anchor: keep the burger physical");
assert(legacyMovementLedSupport || persistentJourneySupport, "CP.1E.6-family runtime must retain movement-led or persistent physical support staging.");
assert(layout.includes("One continuous lateral/arc move") && layout.includes("const sweepX = lerp(-0.72, 0.82, sweep)"), "CP.1E.6 recap continuity invariant is missing.");
assert(runtime.includes("requiredDistance") && runtime.includes("tanHorizontal") && runtime.includes("tanVertical") && !runtime.includes("for (let pass = 0; pass < 4; pass += 1)"), "CP.1E.6-family runtime must preserve analytic crop protection.");
const stableLegacyLighting = runtime.includes("Stable cinematic key/fill/rim rig");
const cameraAwareSuccessor = runtime.includes("CameraAwareStudioRig") && runtime.includes("Screen-space studio lighting follows the master camera");
assert(stableLegacyLighting || cameraAwareSuccessor, "CP.1E.6-family runtime must retain stable cinematic lighting.");
assert((runtime.match(/onPlaybackTime\(timelineTimeS\);/g) ?? []).length === 1, "CP.1E.6 should notify the page clock once per UI update.");
assert(runtime.includes('frameloop="demand"') && runtime.includes('powerPreference: "low-power"') && (runtime.match(/<Canvas\b/g) ?? []).length === 1, "CP.1E.6 must preserve the single low-overhead cinematic runtime.");
console.log("Cinematic Production CP.1E.6-family continuous-choreography verification passed.");
