export const TOO_VAGUE_LABELS = new Set([
  "this",
  "that",
  "it",
  "thing",
  "things",
  "stuff",
  "part",
  "parts",
  "formula",
  "equation",
  "graph",
  "chapter",
  "textbook",
  "problem",
  "problems",
  "help",
  "question",
  "questions",
  "topic",
  "topics",
  "concept",
  "concepts",
  "idea",
  "ideas",
  "material",
  "content",
  "class",
  "lecture",
  "notes",
  "school",
  "science",
  "math",
  "law",
  "history",
  "biology",
  "chemistry",
  "physics",
  "difference",
  "different",
  "again",
  "want",
  "need",
  "think",
  "quiz",
  "go",
  "back",
  "exact",
  "exact part",
  "specific thing",
  "specific",
  "thing",
  "going on",
  "never mind",
  "get it",
  "understanding",
  "not understanding",
  "every time",
  "everyone else",
  "scoring part",
  "sweeping part",
  "first part",
  "second part",
  "first one",
  "second one",
  "that one",
  "that part",
  "this part",
  "real issue",
  "quick side question",
  "keep forgetting",
  "keeps messing",
  "happens right",
  "no the second part",
  "but shorter",
  "thanks that helped",
  "show me another example",
  "can you say that",
  "wait",
  "what do you mean",
  "go back",
  "never mind go back",
  "comes up",
  "especially",
  "especially the scoring part",
  "i",
  "me",
  "you",
  "we",
  "they",
  "he",
  "she",
  "them",
  "us",
]);

export const GENERIC_STARTERS = [
  "a ",
  "an ",
  "the ",
  "this ",
  "that ",
  "these ",
  "those ",
  "my ",
  "our ",
  "their ",
];

export const TRAILING_NOISE_TOKENS = new Set([
  "now",
  "again",
  "today",
  "first",
  "instead",
  "please",
  "better",
  "though",
  "too",
  "still",
  "before",
  "because",
]);

export const NEGATION_STEM_TOKENS = new Set([
  "don",
  "doesn",
  "didn",
  "isn",
  "aren",
  "wasn",
  "weren",
  "won",
  "wouldn",
  "couldn",
  "shouldn",
  "hasn",
  "haven",
  "hadn",
  "mustn",
  "needn",
]);

export const CONTEXT_SHELL_REGEXES: RegExp[] = [
  /^(?:my\s+)?textbook\s+has$/i,
  /^(?:my\s+)?textbook\s+mentions$/i,
  /^(?:my\s+)?notes\s+mention$/i,
  /^(?:my\s+)?notes\s+say$/i,
  /^(?:we\s+)?learned\s+about$/i,
  /^(?:it\s+)?talks\s+about$/i,
  /^(?:there\s+is|there s)\s+(?:a|an|the)?$/i,
  /^(?:my\s+)?textbook$/i,
  /^(?:my\s+)?notes$/i,
  /^textbook\s+has$/i,
  /^formula\s+about$/i,
];

export const FOCUS_MARKER_REGEX =
  /\b(mainly|mostly|especially|specifically|particularly|the part|the thing|most of all|primarily|exactly|real issue|actual issue)\b/i;

export const CONFUSION_MARKER_REGEX =
  /\b(i don't understand|i dont understand|i'm confused|i am confused|im confused|confused about|help me understand|help me with|i need help with|i need help understanding|struggling with|i'm stuck on|i am stuck on|im stuck on|i'm having trouble with|i am having trouble with|im having trouble with|i have trouble with|i don't get|i dont get|can't figure out|cannot figure out|can t figure out|i get lost|doesn't click|doesnt click|not clicking|keep mixing up|mixing up)\b/i;

export const REQUEST_MARKER_REGEX =
  /\b(can we go over|could we go over|walk me through|explain|can you explain|quiz me on|test me on|ask me about|i want to learn about|if i want to learn about|where should i start with|where do i start with|how should i start with|how do i start with|go back to|switch to|work on|show me another example|say that again|can you say that again|what do you mean|go back)\b/i;

export const CONTEXT_MARKER_REGEX =
  /\b(textbook|chapter|notes|teacher|lecture|class|syllabus|worksheet|formula|equation|graph|unit|homework)\b/i;

export const FILLER_WORDS = new Set([
  "really",
  "honestly",
  "basically",
  "just",
  "actually",
  "still",
  "kind",
  "sort",
  "please",
  "again",
  "better",
  "more",
  "clearly",
  "maybe",
  "seriously",
  "exactly",
  "uhh",
  "uh",
  "yeah",
  "well",
  "also",
  "ok",
  "okay",
]);

export const FUNCTION_WORDS = new Set([
  "a",
  "an",
  "the",
  "this",
  "that",
  "these",
  "those",
  "my",
  "our",
  "their",
  "your",
  "its",
  "and",
  "or",
  "but",
  "if",
  "then",
  "than",
  "to",
  "of",
  "for",
  "from",
  "in",
  "on",
  "at",
  "by",
  "with",
  "about",
  "into",
  "through",
  "during",
  "after",
  "before",
  "under",
  "over",
  "between",
  "among",
  "is",
  "are",
  "am",
  "was",
  "were",
  "be",
  "being",
  "been",
  "do",
  "does",
  "did",
  "can",
  "could",
  "would",
  "should",
  "will",
  "why",
  "what",
  "when",
  "where",
  "how",
  "whether",
  "because",
  "maybe",
  "i",
  "me",
  "we",
  "you",
  "they",
  "he",
  "she",
  "them",
  "us",
]);

export const CLAUSE_WORDS = new Set([
  "how",
  "why",
  "what",
  "when",
  "where",
  "whether",
  "if",
  "can",
  "could",
  "would",
  "should",
  "does",
  "do",
  "did",
  "is",
  "are",
  "am",
  "was",
  "were",
  "work",
  "works",
  "happen",
  "happens",
  "affect",
  "influence",
  "impact",
  "change",
  "shape",
  "mean",
  "means",
  "use",
  "uses",
  "start",
  "figure",
]);

export const BAD_SINGLE_TOKENS = new Set([
  "t",
  "m",
  "re",
  "ve",
  "ll",
  "d",
  "s",
  "u",
  "w",
]);

export const PROCESS_PHRASE_REGEXES: RegExp[] = [
  /^(?:t\s+)?figure out$/i,
  /^(?:t\s+)?figure out how$/i,
  /^work$/i,
  /^works$/i,
  /^work out$/i,
  /^understand$/i,
  /^understanding$/i,
  /^learn$/i,
  /^learn about$/i,
  /^where to start$/i,
  /^how to start$/i,
  /^start$/i,
  /^where should i start$/i,
  /^how should i start$/i,
  /^where do i start$/i,
  /^how do i start$/i,
  /^don t know where to start$/i,
  /^dont know where to start$/i,
  /^can t figure out$/i,
  /^cant figure out$/i,
  /^go$/i,
  /^go back$/i,
  /^want$/i,
  /^need$/i,
  /^think$/i,
  /^quiz$/i,
  /^again$/i,
  /^exact part$/i,
  /^going on$/i,
  /^never mind$/i,
  /^different$/i,
  /^not understanding$/i,
  /^keep mixing up$/i,
  /^specific thing$/i,
  /^every time$/i,
  /^especially$/i,
  /^especially the scoring part$/i,
  /^quick side question$/i,
  /^real issue$/i,
  /^keep forgetting$/i,
  /^show me another example$/i,
  /^but shorter$/i,
  /^thanks that helped$/i,
  /^what do you mean$/i,
  /^first one$/i,
  /^first part$/i,
  /^second part$/i,
];

export const FORCE_TOPIC_FALLBACK_PHRASES: RegExp[] = [
  /^(?:can we go over that again)\??$/i,
  /^(?:can we go over it again)\??$/i,
  /^(?:can we do that again)\??$/i,
  /^(?:i still (?:don't|dont) (?:really )?get it)\.?$/i,
  /^(?:can you quiz me on it)\??$/i,
  /^(?:quiz me on it)\??$/i,
  /^(?:can you quiz me on that)\??$/i,
  /^(?:quiz me on that)\??$/i,
  /^(?:yeah[, ]+that exact part)\.?$/i,
  /^(?:i think that'?s the part where i get lost every time)\.?$/i,
  /^(?:can we go over that again, especially .+)\??$/i,
  /^(?:especially the scoring part)\.?$/i,
  /^(?:show me another example)\.?$/i,
  /^(?:can you say that again(?: but shorter)?)\??$/i,
  /^(?:say that again(?: but shorter)?)\??$/i,
  /^(?:wait(?:,? what do you mean)?)\??$/i,
  /^(?:what do you mean)\??$/i,
  /^(?:thanks(?:,? that helped)?)\.?$/i,
  /^(?:yeah,? it'?s that one that keeps messing me up)\.?$/i,
  /^(?:no,? the (?:first|second) part(?: of that)?)\.?$/i,
  /^(?:ok(?:ay)? back to the first one)\.?$/i,
  /^(?:never mind,? go back)\.?$/i,
];

export const TYPO_NORMALIZATION_MAP: Record<string, string> = {
  reuptaek: "reuptake",
  dont: "don't",
  pls: "",
  u: "",
  w: "",
};

export const TRAILING_TOPIC_TAIL_REGEXES: RegExp[] = [
  /\bwork$/i,
  /\bworks$/i,
  /\band i$/i,
  /\band everyone else(?: seems to get.*)?$/i,
  /\bcomes up$/i,
  /\bin a simpler(?: way)?$/i,
  /\bespecially the scoring part$/i,
  /\band what makes a shot count$/i,
  /\bin neurons$/i,
  /\bthing from physics$/i,
  /\bthing from physics because$/i,
  /\bfrom physics$/i,
  /\bfrom physics because$/i,
  /\bbecause$/i,
  /\bbefore$/i,
  /\bpart$/i,
  /\bfor me$/i,
  /\bbut shorter$/i,
];

export const LEADING_STRIP_REGEXES: RegExp[] = [
  /^(?:quick\s+side\s+question)\b[:, ]*/i,
  /^(?:real\s+issue)\b[:, ]*/i,
  /^(?:the\s+real\s+issue\s+for\s+me\s+is)\s+/i,
  /^(?:what\s+i\s+need\s+help\s+with\s+is)\s+/i,
  /^(?:what\s+i\s+actually\s+don'?t\s+understand\s+is)\s+/i,
  /^(?:the\s+specific\s+thing\s+i\s+want\s+to\s+go\s+over\s+now\s+is)\s+/i,
  /^(?:specific\s+thing\s+i\s+want\s+to\s+go\s+over\s+now\s+is)\s+/i,
  /^(?:the\s+part\s+that\s+is\s+messing\s+me\s+up\s+is)\s+/i,
  /^(?:the\s+thing\s+i\s+actually\s+don'?t\s+get\s+is)\s+/i,
  /^(?:at\s+first\s+i\s+thought\s+the\s+hard\s+part\s+was\s+.+?,\s+but\s+actually\s+what\s+i\s+need\s+help\s+with\s+is)\s+/i,
];