// lib/runtime/topic-labeling/topic-label-constants.ts
// Updated constants for discourse-first deterministic topic labeling.

export const TOO_VAGUE_LABELS = new Set([
  "this",
  "that",
  "it",
  "thing",
  "things",
  "stuff",
  "part",
  "parts",
  "bit",
  "bits",
  "point",
  "points",
  "section",
  "unit",
  "formula",
  "equation",
  "graph",
  "chapter",
  "textbook",
  "worksheet",
  "homework",
  "problem",
  "problems",
  "help",
  "question",
  "questions",
  "topic",
  "topics",
  "concept",
  "concepts",
  "idea",
  "ideas",
  "material",
  "content",
  "class",
  "lecture",
  "notes",
  "school",
  "science",
  "math",
  "law",
  "history",
  "biology",
  "chemistry",
  "physics",
  "english",
  "spanish",
  "tax",
  "taxes",
  "finance",
  "economics",
  "programming",
  "coding",
  "difference",
  "different",
  "same",
  "again",
  "want",
  "need",
  "think",
  "guess",
  "quiz",
  "test",
  "go",
  "back",
  "exact",
  "specific",
  "exact part",
  "specific thing",
  "actual thing",
  "actual issue",
  "actual problem",
  "actual blocker",
  "real issue",
  "real problem",
  "real bottleneck",
  "main bottleneck",
  "blocker",
  "target",
  "going on",
  "what is going on",
  "what's going on",
  "never mind",
  "get it",
  "understanding",
  "not understanding",
  "every time",
  "everyone else",
  "scoring part",
  "sweeping part",
  "first part",
  "second part",
  "first one",
  "second one",
  "that one",
  "that part",
  "this part",
  "tiny word",
  "small words",
  "quick side question",
  "keep forgetting",
  "keeps messing",
  "happens right",
  "no the second part",
  "but shorter",
  "thanks that helped",
  "show me another example",
  "can you say that",
  "say that again",
  "wait",
  "what do you mean",
  "go back",
  "never mind go back",
  "comes up",
  "came up",
  "showed up",
  "not clicking",
  "not clicking rn",
  "where to start",
  "where to even start",
  "i don't know where to start",
  "i dont know where to start",
  "coded language",
  "another language",
  "feels coded",
  "it feels coded",
  "whole thing",
  "whole thing confusing",
  "missing piece",
  "own brain",
  "my brain",
  "i'm confused",
  "im confused",
  "i am confused",
  "i don't get",
  "i dont get",
  "i don't understand",
  "i dont understand",
  "i'm stuck",
  "im stuck",
  "i am stuck",
  "i'm lost",
  "im lost",
  "i am lost",
  "bc im lost",
  "especially",
  "especially the scoring part",
  "i",
  "me",
  "you",
  "we",
  "they",
  "he",
  "she",
  "them",
  "us",
]);

export const GENERIC_STARTERS = [
  "a ",
  "an ",
  "the ",
  "this ",
  "that ",
  "these ",
  "those ",
  "my ",
  "our ",
  "their ",
  "your ",
  "some ",
  "any ",
];

export const TRAILING_NOISE_TOKENS = new Set([
  "now",
  "again",
  "today",
  "first",
  "instead",
  "please",
  "better",
  "though",
  "too",
  "still",
  "before",
  "because",
  "yet",
  "rn",
  "bc",
  "honestly",
  "really",
  "basically",
  "actually",
  "seriously",
  "tbh",
  "lol",
  "pls",
  "plz",
]);

export const NEGATION_STEM_TOKENS = new Set([
  "don",
  "doesn",
  "didn",
  "isn",
  "aren",
  "wasn",
  "weren",
  "won",
  "wouldn",
  "couldn",
  "shouldn",
  "hasn",
  "haven",
  "hadn",
  "mustn",
  "needn",
  "cant",
  "cannot",
]);

export const CONTEXT_SHELL_REGEXES: RegExp[] = [
  /^(?:my\s+)?textbook\s+has$/i,
  /^(?:my\s+)?textbook\s+mentions$/i,
  /^(?:my\s+)?notes\s+mention$/i,
  /^(?:my\s+)?notes\s+say$/i,
  /^(?:we\s+)?learned\s+about$/i,
  /^(?:we\s+)?started\s+(?:a\s+)?(?:section|unit|chapter)\s+on$/i,
  /^(?:we\s+)?are\s+doing$/i,
  /^(?:we'?re\s+)?doing$/i,
  /^(?:it\s+)?talks\s+about$/i,
  /^(?:there\s+is|there s)\s+(?:a|an|the)?$/i,
  /^(?:my\s+)?textbook$/i,
  /^(?:my\s+)?notes$/i,
  /^textbook\s+has$/i,
  /^formula\s+about$/i,
  /^equation\s+about$/i,
  /^worksheet\s+switched\s+to$/i,
  /^the\s+worksheet\s+switched\s+to$/i,
  /^class\s+topic$/i,
  /^big\s+topic$/i,
  /^bigger\s+topic$/i,
  /^general\s+topic$/i,
  /^overall\s+topic$/i,
];

export const FOCUS_MARKER_REGEX =
  /\b(mainly|mostly|especially|specifically|particularly|the part|the thing|the bit|most of all|primarily|exactly|real issue|actual issue|real problem|actual problem|real bottleneck|main bottleneck|actual blocker|the blocker|specific point|specific thing|what i actually|what i really|right now|the target|the actual target|what keeps|throwing me off|tripping me up|where i start|get stuck on|stuck on|not vocab|not the general|not really what)\b/i;

export const CONFUSION_MARKER_REGEX =
  /\b(i don't understand|i dont understand|i do not understand|i'm confused|i am confused|im confused|confused about|help me understand|help me with|i need help with|i need help understanding|struggling with|i'm stuck on|i am stuck on|im stuck on|i'm having trouble with|i am having trouble with|im having trouble with|i have trouble with|i don't get|i dont get|i do not get|can't figure out|cant figure out|cannot figure out|can t figure out|i get lost|i keep getting lost|i lose track|doesn't click|doesnt click|does not click|not clicking|keep mixing up|mixing up|blending together|blur together|feel interchangeable|feel basically the same|seem basically the same|stopped following|stop following|falls apart|breaks my understanding|stops making sense|throwing me off|tripping me up|messing me up|keeps messing me up|makes me shut down|makes me freeze|feel lost|feel behind|feel stupid|feel dumb|panic|spiral)\b/i;

export const REQUEST_MARKER_REGEX =
  /\b(can we go over|could we go over|walk me through|explain|can you explain|quiz me on|test me on|ask me about|i want to learn about|i would like to learn about|i would really like to learn about|if i want to learn about|where should i start with|where do i start with|how should i start with|how do i start with|go back to|switch to|work on|show me another example|say that again|can you say that again|what do you mean|go back|help me understand|help me with|i need help with|i need help understanding|can i get some help with|could i get some help with|can you help me with|could you help me with)\b/i;

export const CONTEXT_MARKER_REGEX =
  /\b(textbook|chapter|notes|teacher|lecture|class|syllabus|worksheet|formula|equation|graph|unit|homework|section|practice questions|practice question|slide|slides|lesson|reviewing|we started|we'?re doing|we are doing|in class|this week|teacher explained)\b/i;

export const FILLER_WORDS = new Set([
  "really",
  "honestly",
  "basically",
  "just",
  "actually",
  "still",
  "kind",
  "sort",
  "please",
  "again",
  "better",
  "more",
  "clearly",
  "maybe",
  "seriously",
  "exactly",
  "uhh",
  "uh",
  "yeah",
  "well",
  "also",
  "ok",
  "okay",
  "rn",
  "tbh",
  "lol",
  "ngl",
  "like",
  "literally",
  "probably",
  "eventually",
  "somehow",
]);

export const FUNCTION_WORDS = new Set([
  "a",
  "an",
  "the",
  "this",
  "that",
  "these",
  "those",
  "my",
  "our",
  "their",
  "your",
  "its",
  "and",
  "or",
  "but",
  "if",
  "then",
  "than",
  "to",
  "of",
  "for",
  "from",
  "in",
  "on",
  "at",
  "by",
  "with",
  "about",
  "into",
  "through",
  "during",
  "after",
  "before",
  "under",
  "over",
  "between",
  "among",
  "is",
  "are",
  "am",
  "was",
  "were",
  "be",
  "being",
  "been",
  "do",
  "does",
  "did",
  "can",
  "could",
  "would",
  "should",
  "will",
  "why",
  "what",
  "when",
  "where",
  "how",
  "whether",
  "because",
  "maybe",
  "i",
  "me",
  "we",
  "you",
  "they",
  "he",
  "she",
  "them",
  "us",
]);

export const CLAUSE_WORDS = new Set([
  "how",
  "why",
  "what",
  "when",
  "where",
  "whether",
  "if",
  "can",
  "could",
  "would",
  "should",
  "does",
  "do",
  "did",
  "is",
  "are",
  "am",
  "was",
  "were",
  "work",
  "works",
  "happen",
  "happens",
  "affect",
  "influence",
  "impact",
  "change",
  "changes",
  "shape",
  "shapes",
  "mean",
  "means",
  "use",
  "uses",
  "start",
  "starts",
  "started",
  "stop",
  "stops",
  "stopped",
  "figure",
  "clicking",
  "showed",
  "came",
  "comes",
  "confused",
  "lost",
  "stuck",
  "feel",
  "feels",
]);

export const BAD_SINGLE_TOKENS = new Set([
  "t",
  "m",
  "re",
  "ve",
  "ll",
  "d",
  "s",
  "u",
  "w",
  "n",
  "idk",
]);

export const PROCESS_PHRASE_REGEXES: RegExp[] = [
  /^(?:t\s+)?figure out$/i,
  /^(?:t\s+)?figure out how$/i,
  /^work$/i,
  /^works$/i,
  /^work out$/i,
  /^understand$/i,
  /^understanding$/i,
  /^learn$/i,
  /^learn about$/i,
  /^where to start$/i,
  /^where to even start$/i,
  /^how to start$/i,
  /^start$/i,
  /^where should i start$/i,
  /^how should i start$/i,
  /^where do i start$/i,
  /^how do i start$/i,
  /^don t know where to start$/i,
  /^dont know where to start$/i,
  /^do not know where to start$/i,
  /^can t figure out$/i,
  /^cant figure out$/i,
  /^cannot figure out$/i,
  /^go$/i,
  /^go back$/i,
  /^want$/i,
  /^need$/i,
  /^think$/i,
  /^guess$/i,
  /^quiz$/i,
  /^test$/i,
  /^again$/i,
  /^exact part$/i,
  /^specific thing$/i,
  /^actual thing$/i,
  /^actual blocker$/i,
  /^actual issue$/i,
  /^real issue$/i,
  /^real bottleneck$/i,
  /^blocker$/i,
  /^target$/i,
  /^going on$/i,
  /^what is going on$/i,
  /^what s going on$/i,
  /^never mind$/i,
  /^different$/i,
  /^not understanding$/i,
  /^keep mixing up$/i,
  /^every time$/i,
  /^especially$/i,
  /^especially the scoring part$/i,
  /^quick side question$/i,
  /^keep forgetting$/i,
  /^show me another example$/i,
  /^but shorter$/i,
  /^thanks that helped$/i,
  /^what do you mean$/i,
  /^first one$/i,
  /^first part$/i,
  /^second part$/i,
  /^that part$/i,
  /^this part$/i,
  /^that exact part$/i,
  /^that specific part$/i,
  /^tiny word$/i,
  /^small words$/i,
  /^coded language$/i,
  /^another language$/i,
  /^feels coded$/i,
  /^it feels coded$/i,
  /^i'?m confused$/i,
  /^im confused$/i,
  /^i am confused$/i,
  /^i'?m stuck$/i,
  /^im stuck$/i,
  /^i am stuck$/i,
  /^i'?m lost$/i,
  /^im lost$/i,
  /^i am lost$/i,
  /^not clicking$/i,
  /^not clicking rn$/i,
  /^came up$/i,
  /^comes up$/i,
  /^showed up$/i,
  /^formula came up$/i,
  /^that i don'?t get$/i,
  /^that i dont get$/i,
  /^that i do not get$/i,
  /^and i don'?t$/i,
  /^and i dont$/i,
  /^and i do not$/i,
  /^are what i keep$/i,
  /^bc im lost$/i,
  /^because im lost$/i,
  /^works in soccer$/i,
];

export const FORCE_TOPIC_FALLBACK_PHRASES: RegExp[] = [
  /^(?:can we go over that again)\??$/i,
  /^(?:can we go over it again)\??$/i,
  /^(?:can we go over this again)\??$/i,
  /^(?:can we do that again)\??$/i,
  /^(?:can we do it again)\??$/i,
  /^(?:can we do another example of that)\??$/i,
  /^(?:can we do another example of it)\??$/i,
  /^(?:can we go over that again,? but slower(?: this time)?)\??$/i,
  /^(?:can we go over it again,? but slower(?: this time)?)\??$/i,
  /^(?:can we go over that again,? especially .+)\??$/i,
  /^(?:i still (?:don't|dont|do not) (?:really )?get it)\.?$/i,
  /^(?:i still (?:don't|dont|do not) (?:really )?understand it)\.?$/i,
  /^(?:can you quiz me on it)\??$/i,
  /^(?:quiz me on it)\??$/i,
  /^(?:can you quiz me on that)\??$/i,
  /^(?:quiz me on that)\??$/i,
  /^(?:can you test me on it)\??$/i,
  /^(?:test me on it)\??$/i,
  /^(?:can you test me on that)\??$/i,
  /^(?:test me on that)\??$/i,
  /^(?:yeah[, ]+that exact part)\.?$/i,
  /^(?:yeah[, ]+that specific part)\.?$/i,
  /^(?:yeah[, ]+that tiny word)\.?$/i,
  /^(?:yeah[, ]+that is what i mean)\.?$/i,
  /^(?:yes[, ]+that tiny word is the thing that breaks my confidence)\.?$/i,
  /^(?:that is the exact mix-up,? yeah)\.?$/i,
  /^(?:that'?s the exact mix-up,? yeah)\.?$/i,
  /^(?:i think that'?s the part where i get lost every time)\.?$/i,
  /^(?:especially the scoring part)\.?$/i,
  /^(?:show me another example)\.?$/i,
  /^(?:can you say that again(?: but shorter)?)\??$/i,
  /^(?:say that again(?: but shorter)?)\??$/i,
  /^(?:wait(?:,? what do you mean)?)\??$/i,
  /^(?:what do you mean)\??$/i,
  /^(?:thanks(?:,? that helped)?)\.?$/i,
  /^(?:yeah,? it'?s that one that keeps messing me up)\.?$/i,
  /^(?:no,? the (?:first|second) part(?: of that)?)\.?$/i,
  /^(?:ok(?:ay)? back to the first one)\.?$/i,
  /^(?:never mind,? go back)\.?$/i,
  /^(?:it just feels coded,? honestly)\.?$/i,
  /^(?:it just feels coded)\.?$/i,
  /^(?:it just feels like another language)\.?$/i,
  /^(?:that exact part is what made me feel lost)\.?$/i,
  /^(?:that is the exact part,? yeah)\.?$/i,
  /^(?:can we do that again)\??$/i,
  /^(?:can you test me on that)\??$/i,
];

export const TYPO_NORMALIZATION_MAP: Record<string, string> = {
  reuptaek: "reuptake",
  reuptke: "reuptake",
  reutpake: "reuptake",
  depolarisation: "depolarization",
  depolariztion: "depolarization",
  electronegativityy: "electronegativity",
  neurotransmision: "neurotransmission",
  neurotransmisson: "neurotransmission",
  neurotransmiters: "neurotransmitters",
  nuerotransmitters: "neurotransmitters",
  osomsis: "osmosis",
  osmois: "osmosis",
  mitosiss: "mitosis",
  meosis: "meiosis",
  metaphse: "metaphase",
  anaphse: "anaphase",
  refractoryy: "refractory",
  refratory: "refractory",
  stnadard: "standard",
  devation: "deviation",
  oppurtunity: "opportunity",
  oportunity: "opportunity",
  subducton: "subduction",
  dominents: "dominants",
  secundary: "secondary",
  interst: "interest",
  deductable: "deductible",
  premimum: "premium",
  prinicpal: "principal",
  principale: "principal",
  buget: "budget",
  bugeting: "budgeting",
  balence: "balance",
  balences: "balances",
  spanishh: "spanish",
  sentance: "sentence",
  vocab: "vocab",
  dont: "don't",
  cant: "can't",
  doesnt: "doesn't",
  isnt: "isn't",
  wasnt: "wasn't",
  couldnt: "couldn't",
  shouldnt: "shouldn't",
  wouldnt: "wouldn't",
  im: "i'm",
  idk: "i don't know",
  bc: "because",
  cuz: "because",
  tho: "though",
  till: "until",
  rn: "",
  pls: "",
  plz: "",
  u: "",
  w: "",
  n: "and",
  knwo: "know",
  bettter: "better",
  teh: "the",
  hte: "the",
  llm: "llm",
  llms: "llms",
};

export const TRAILING_TOPIC_TAIL_REGEXES: RegExp[] = [
  /\bwork$/i,
  /\bworks$/i,
  /\band i$/i,
  /\band everyone else(?: seems to get.*)?$/i,
  /\bcomes up$/i,
  /\bcame up$/i,
  /\bshowed up$/i,
  /\bshowed up again$/i,
  /\bshows up again$/i,
  /\bformula$/i,
  /\bformula came up$/i,
  /\bformula shows up$/i,
  /\bshowed up,? and then.*$/i,
  /\bcame up,? and now.*$/i,
  /\bin a simpler(?: way)?$/i,
  /\bespecially the scoring part$/i,
  /\band what makes a shot count$/i,
  /\bin neurons$/i,
  /\bthing from physics$/i,
  /\bthing from physics because$/i,
  /\bfrom physics$/i,
  /\bfrom physics because$/i,
  /\bbecause$/i,
  /\bbefore$/i,
  /\bpart$/i,
  /\bfor me$/i,
  /\bbut shorter$/i,
  /\bthat i don'?t get$/i,
  /\bthat i dont get$/i,
  /\bthat i do not get$/i,
  /\band i don'?t$/i,
  /\band i dont$/i,
  /\band i do not$/i,
  /\bare what i keep$/i,
  /\bwhat i keep$/i,
  /\bbc i'?m lost$/i,
  /\bbc im lost$/i,
  /\bbecause i'?m lost$/i,
  /\bnot clicking$/i,
  /\bnot clicking rn$/i,
  /\bworks in soccer$/i,
  /\bis what i'?m confused about$/i,
  /\bis what im confused about$/i,
  /\bis what i am confused about$/i,
  /\bis what i keep getting stuck on$/i,
  /\bthat i do not really understand$/i,
  /\bthat i don'?t really understand$/i,
  /\bthat i dont really understand$/i,
  /\bthe whole thing confusing to me$/i,
  /\bthe whole thing confusing$/i,
  /\bi do not really understand$/i,
  /\bi don'?t really understand$/i,
  /\bi dont really understand$/i,
  /\bbecause i can(?:not|'?t) picture.*$/i,
  /\bbecause i cannot picture.*$/i,
  /\bbecause i can'?t picture.*$/i,
  /\bbecause i do not know.*$/i,
  /\bbecause i don'?t know.*$/i,
  /\bbecause i dont know.*$/i,
  /\bbecause every explanation.*$/i,
  /\bbecause people describe it.*$/i,
  /\bbecause that is where.*$/i,
  /\bbecause that's where.*$/i,
  /\band then suddenly.*$/i,
  /\band suddenly.*$/i,
  /\band i start feeling.*$/i,
  /\band i feel.*$/i,
  /\bfeel(?:s)? like coded language.*$/i,
  /\blike coded language.*$/i,
  /\bwritten for somebody.*$/i,
  /\bwhere i stopped following.*$/i,
  /\bwhere i stop following.*$/i,
  /\bwhere i start getting lost.*$/i,
  /\bwhere things stop making sense.*$/i,
];

export const LEADING_STRIP_REGEXES: RegExp[] = [
  /^(?:quick\s+side\s+question)\b[:, ]*/i,
  /^(?:real\s+issue)\b[:, ]*/i,
  /^(?:actual\s+issue)\b[:, ]*/i,
  /^(?:actual\s+blocker)\b[:, ]*/i,
  /^(?:the\s+real\s+issue\s+for\s+me\s+is)\s+/i,
  /^(?:the\s+real\s+issue\s+is)\s+/i,
  /^(?:the\s+actual\s+issue\s+is)\s+/i,
  /^(?:the\s+actual\s+problem\s+is)\s+/i,
  /^(?:the\s+actual\s+blocker\s+is)\s+/i,
  /^(?:the\s+blocker\s+is)\s+/i,
  /^(?:the\s+real\s+bottleneck\s+is)\s+/i,
  /^(?:the\s+main\s+bottleneck\s+is)\s+/i,
  /^(?:right\s+now\s+the\s+actual\s+blocker\s+is)\s+/i,
  /^(?:right\s+now\s+the\s+blocker\s+is)\s+/i,
  /^(?:what\s+i\s+need\s+help\s+with\s+is)\s+/i,
  /^(?:what\s+i\s+actually\s+need\s+help\s+with\s+is)\s+/i,
  /^(?:what\s+i\s+actually\s+don'?t\s+understand\s+is)\s+/i,
  /^(?:what\s+i\s+actually\s+dont\s+understand\s+is)\s+/i,
  /^(?:what\s+i\s+really\s+don'?t\s+understand\s+is)\s+/i,
  /^(?:what\s+i\s+really\s+dont\s+understand\s+is)\s+/i,
  /^(?:what\s+i\s+actually\s+keep\s+getting\s+stuck\s+on\s+is)\s+/i,
  /^(?:the\s+specific\s+thing\s+i\s+want\s+to\s+go\s+over\s+now\s+is)\s+/i,
  /^(?:specific\s+thing\s+i\s+want\s+to\s+go\s+over\s+now\s+is)\s+/i,
  /^(?:the\s+specific\s+thing\s+i\s+need\s+to\s+understand\s+is)\s+/i,
  /^(?:the\s+specific\s+thing\s+i\s+need\s+help\s+with\s+is)\s+/i,
  /^(?:the\s+specific\s+thing\s+i\s+want\s+to\s+fix\s+is)\s+/i,
  /^(?:what\s+i\s+want\s+to\s+fix\s+is)\s+/i,
  /^(?:the\s+part\s+that\s+is\s+messing\s+me\s+up\s+is)\s+/i,
  /^(?:the\s+thing\s+i\s+actually\s+don'?t\s+get\s+is)\s+/i,
  /^(?:the\s+thing\s+i\s+actually\s+dont\s+get\s+is)\s+/i,
  /^(?:the\s+thing\s+i\s+don'?t\s+get\s+is)\s+/i,
  /^(?:the\s+thing\s+i\s+dont\s+get\s+is)\s+/i,
  /^(?:the\s+part\s+i\s*(?:am|'?m)?\s*actually\s+confused\s+about\s+is)\s+/i,
  /^(?:the\s+part\s+that\s+seems\s+to\s+stop\s+me\s+every\s+time\s+is)\s+/i,
  /^(?:the\s+thing\s+that'?s\s+throwing\s+me\s+off\s+is)\s+/i,
  /^(?:what\s+keeps\s+tripping\s+me\s+up\s+is)\s+/i,
  /^(?:the\s+only\s+part\s+that\s+doesn'?t\s+click\s+is)\s+/i,
  /^(?:the\s+bit\s+that\s+confuses\s+me\s+most\s+is)\s+/i,
  /^(?:where\s+i\s+start\s+getting\s+lost\s+is)\s+/i,
  /^(?:where\s+i\s+stopped\s+following\s+is)\s+/i,
  /^(?:at\s+first\s+i\s+thought\s+the\s+hard\s+part\s+was\s+.+?,\s+but\s+actually\s+what\s+i\s+need\s+help\s+with\s+is)\s+/i,
  /^(?:at\s+first\s+i\s+thought\s+.+?,\s+but\s+after\s+looking\s+again\s+i\s+think\s+it'?s\s+really\s+just)\s+/i,
  /^(?:after\s+looking\s+again\s+i\s+think\s+it'?s\s+really\s+just)\s+/i,
];
