export const blindV2Isolated = [
  {
    id: "blindv2-direct-001",
    category: "direct",
    description: "direct concrete biology topic",
    message: "Can we go over membrane potentials?",
    expectedLabel: "Membrane Potentials",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-direct-002",
    category: "direct",
    description: "direct abstract AI topic",
    message: "I would really like to learn about how llms work and why deterministic code can't solve all my problems.",
    expectedLabel: "How LLMs Work",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-direct-003",
    category: "direct",
    description: "direct finance topic",
    message: "Can you help me understand amortization?",
    expectedLabel: "Amortization",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-focus-001",
    category: "broad_to_narrow",
    description: "broad message with sharper subfocus",
    message: "I'm learning about neurons, but the sodium-potassium pump is the actual thing I don't get.",
    expectedLabel: "Sodium-Potassium Pump",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-focus-002",
    category: "broad_to_narrow",
    description: "broad math topic narrowed to specific concept",
    message: "Statistics is fine overall, but standard deviation is where I keep getting lost.",
    expectedLabel: "Standard Deviation",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-focus-003",
    category: "broad_to_narrow",
    description: "broad chemistry topic narrowed by confusion target",
    message: "The chapter is on acids and bases, but what I'm really confused about is pH.",
    expectedLabel: "pH",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-compare-001",
    category: "comparison",
    description: "comparison phrased with mixing-up wrapper",
    message: "I keep mixing up kinetic energy and potential energy.",
    expectedLabel: "Kinetic Energy vs Potential Energy",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-compare-002",
    category: "comparison",
    description: "explicit compare request with determiners",
    message: "Can you compare the sympathetic nervous system and the parasympathetic nervous system?",
    expectedLabel: "Sympathetic Nervous System vs Parasympathetic Nervous System",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-compare-003",
    category: "comparison",
    description: "when-to-use comparison phrasing",
    message: "I keep forgetting when to use mean vs median.",
    expectedLabel: "Mean vs Median",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-domain-001",
    category: "domain_shaping",
    description: "insurance phrasing with other concept",
    message: "What does a premium mean in insurance?",
    expectedLabel: "Insurance Premium",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-domain-002",
    category: "domain_shaping",
    description: "sports concept shaped by domain",
    message: "Can you explain how icing works in hockey?",
    expectedLabel: "Icing in Hockey",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-domain-003",
    category: "domain_shaping",
    description: "finance concept shaped by domain",
    message: "What is principal in a loan?",
    expectedLabel: "Loan Principal",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-tail-001",
    category: "tail_contamination",
    description: "concept plus explanatory residue",
    message: "It's really photosynthesis that I don't get yet.",
    expectedLabel: "Photosynthesis",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-tail-002",
    category: "tail_contamination",
    description: "concept plus casual residue",
    message: "Probability is not clicking for me right now.",
    expectedLabel: "Probability",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-tail-003",
    category: "tail_contamination",
    description: "concept plus event tail",
    message: "I was fine until torque showed up.",
    expectedLabel: "Torque",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-tail-004",
    category: "tail_contamination",
    description: "of-phrase plus discourse tail",
    message: "The rules of baseball are what make the whole thing confusing.",
    expectedLabel: "Rules of Baseball",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-noise-001",
    category: "noisy_natural_language",
    description: "messy lowercase casual phrasing",
    message: "ok wait can u help me w mitosis bc im still lost",
    expectedLabel: "Mitosis",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-noise-002",
    category: "noisy_natural_language",
    description: "messy casual domain-shaped phrasing",
    message: "idk how interest works on student loans tbh",
    expectedLabel: "Interest on Student Loans",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-noise-003",
    category: "noisy_natural_language",
    description: "messy compare phrasing",
    message: "your and youre still mess me up lol",
    expectedLabel: "Your vs You're",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-paragraph-001",
    category: "paragraph_context",
    description: "paragraph with explicit late focus",
    message:
      "We started talking about memory in class, and most of it made sense. Then the hippocampus came up, and that's the part where I stopped understanding what was going on.",
    expectedLabel: "Hippocampus",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-paragraph-002",
    category: "paragraph_context",
    description: "paragraph with formula wrapper",
    message:
      "My textbook has a formula for momentum, and I thought I was following everything. But once that showed up, everyone else seemed ahead of me.",
    expectedLabel: "Momentum",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-paragraph-003",
    category: "paragraph_context",
    description: "paragraph with compare target embedded late",
    message:
      "At first I thought the hard part was mitosis, but after looking again I think it's really just metaphase vs anaphase that I keep blending together.",
    expectedLabel: "Metaphase vs Anaphase",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-paragraph-004",
    category: "paragraph_context",
    description: "paragraph with domain-shaped sports rule",
    message:
      "I can follow most of hockey, but once icing comes up, I lose track of why the play stops and what the rule is doing.",
    expectedLabel: "Icing in Hockey",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-negative-001",
    category: "negative_followup",
    description: "meta continuation that should not create a new topic by itself",
    message: "Can you say that again?",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Photosynthesis",
    expectedShouldCreate: false,
    activeTopicName: "Photosynthesis",
    existingTopics: ["Photosynthesis"],
  },
  {
    id: "blindv2-negative-002",
    category: "negative_followup",
    description: "example request should stay on active topic",
    message: "Show me another example.",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Momentum",
    expectedShouldCreate: false,
    activeTopicName: "Momentum",
    existingTopics: ["Momentum"],
  },
];

export const blindV2Sequence = [
  {
    id: "blindv2-seq-001:step-1",
    category: "followup_continuity",
    description: "create then anaphoric followup",
    message: "Can you help me understand photosynthesis?",
    expectedLabel: "Photosynthesis",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-seq-001:step-2",
    category: "followup_continuity",
    description: "anaphoric stay-on-topic",
    message: "I still don't get it.",
    expectedLabel: "Photosynthesis",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Photosynthesis",
    expectedShouldCreate: false,
  },

  {
    id: "blindv2-seq-002:step-1",
    category: "followup_continuity",
    description: "create then subpart followup",
    message: "Can we go over the rules of baseball?",
    expectedLabel: "Rules of Baseball",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-seq-002:step-2",
    category: "followup_continuity",
    description: "mixed anaphoric plus subpart followup",
    message: "Can we go over that again, especially the scoring part?",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Rules of Baseball",
    expectedShouldCreate: false,
  },

  {
    id: "blindv2-seq-003:step-1",
    category: "followup_continuity",
    description: "create first topic",
    message: "I want to learn about dopamine.",
    expectedLabel: "Dopamine",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-seq-003:step-2",
    category: "followup_continuity",
    description: "switch to second related topic",
    message: "Actually can we switch to serotonin?",
    expectedLabel: "Serotonin",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-seq-003:step-3",
    category: "followup_continuity",
    description: "go back to prior topic explicitly",
    message: "Wait, go back to dopamine.",
    expectedMatchedTopic: "Dopamine",
    expectedShouldCreate: false,
  },

  {
    id: "blindv2-seq-004:step-1",
    category: "followup_continuity",
    description: "comparison topic create",
    message: "Can you compare kinetic energy and potential energy?",
    expectedLabel: "Kinetic Energy vs Potential Energy",
    expectedResolution: "created_new_candidate",
    expectedMatchedTopic: null,
    expectedShouldCreate: true,
  },
  {
    id: "blindv2-seq-004:step-2",
    category: "followup_continuity",
    description: "meta continuation after comparison",
    message: "Wait, what do you mean?",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Kinetic Energy vs Potential Energy",
    expectedShouldCreate: false,
  },

  {
    id: "blindv2-seq-005:step-1",
    category: "followup_continuity",
    description: "existing-topic reuse on direct mention",
    message: "Can I get help with osmosis?",
    expectedLabel: "Osmosis",
    expectedResolution: "matched_existing",
    expectedMatchedTopic: "Osmosis",
    expectedShouldCreate: false,
    existingTopics: ["Osmosis", "Action Potentials"],
  },
  {
    id: "blindv2-seq-005:step-2",
    category: "followup_continuity",
    description: "stay on reused topic with short followup",
    message: "Can we do that again?",
    expectedLabel: "Osmosis",
    expectedResolution: "fallback_active_topic",
    expectedMatchedTopic: "Osmosis",
    expectedShouldCreate: false,
  },
];