// scripts/topic-labeling-naturalistic-diverse.ts

import type { TopicGoldenCase } from "./topic-labeling-goldens";

/**
 * NATURALISTIC DIVERSE GOLDENS
 *
 * This suite is intentionally broader and harder than topic-labeling-holdout.ts.
 * Every message is multi-sentence, naturalistic, and usually includes
 * learner-state residue, implicit focus, typo/noise, or broad-to-narrow structure.
 * About 30% of the cases are deliberately complex question-form messages
 * starting with Who/What/When/Where/Why/How.
 *
 * Goal: prevent the deterministic labeler from overfitting to Spanish/taxes/waves.
 */
export const TOPIC_LABELING_NATURALISTIC_DIVERSE_GOLDENS: TopicGoldenCase[] = [

  // ---------------------------------------------------------------------------
  // COOKING
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-cooking-001",
    description: "implicit heat-control issue inside rambling cooking message",
    message: "I tried making eggs again and I swear the recipe sounded simple. I did not burn them exactly, but the pan went from quiet to chaotic so fast that I think the actual thing I need to understand is heat control.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Heat Control",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cooking]",
  },
  {
    id: "naturalistic-cooking-002",
    description: "sauce problem where emulsification is implied",
    message: "Why does my salad dressing look fine for ten seconds and then seperate again even after I whisk it like crazy? I thought the problem was just mixing harder, but I think the actual thing I do not understand is emulsification.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Emulsification",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cooking]",
  },
  {
    id: "naturalistic-cooking-003",
    description: "knife skills hidden under cooking anxiety",
    message: "How am I supposed to know the difference between dice, mince, and chop when a recipe says it like everyone already knows? I can follow the cooking part once everything is ready, but knife skills are the thing making me freeze.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Knife Skills",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cooking]",
  },
  {
    id: "naturalistic-cooking-004",
    description: "baking texture issue points to gluten development",
    message: "I tried making bread and the dough felt weirdly tough, but I kept pretending that was normal. The recipe mentions kneading and structure and I think gluten development is the part that I never actually understood.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Gluten Development",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cooking]",
  },

  // ---------------------------------------------------------------------------
  // SPORTS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-sports-005",
    description: "basketball defense message with buried zone defense target",
    message: "Why did the basketball team switch defenses if the same players were still on the court? I could follow who scored, kind of, but zone defense is the part I do not actually understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Zone Defense",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:sports]",
  },
  {
    id: "naturalistic-sports-006",
    description: "soccer offside hidden in watching context",
    message: "What makes a soccer play offside when the pass and the run happen almost at the same time? I can see the players moving, but the rule logic still feels like everyone else knows a hidden step.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Offside in Soccer",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:sports]",
  },
  {
    id: "naturalistic-sports-007",
    description: "baseball scoring confusion with earned runs",
    message: "I watched baseball with my cousin and mostly nodded like I understood the stats. The score itself was fine, but earned runs were where I lost track because I could not tell what counted against the pitcher.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Earned Runs",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:sports]",
  },
  {
    id: "naturalistic-sports-008",
    description: "tennis scoring implied by frustration",
    message: "I know tennis points go love and fifteen and all that, but the game suddenly said deuce and advantage and I got lost. The real issue is tennis scoring, not the hitting part.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Tennis Scoring",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:sports]",
  },

  // ---------------------------------------------------------------------------
  // JOBS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-jobs-009",
    description: "job interview topic hidden behind anxiety",
    message: "How do I answer behavioral interview questions without just telling a random story and hoping it sounds professional? I have an interview coming up, and that is the part making me freeze.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Behavioral Interview Questions",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:jobs]",
  },
  {
    id: "naturalistic-jobs-010",
    description: "resume bullet problem from vague career message",
    message: "What makes a resume bullet sound like an accomplishment instead of just a task I was assigned? I tried updating mine, but everything either sounds boring or fake, so accomplishment-based resume bullets are the issue.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Accomplishment-Based Resume Bullets",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:jobs]",
  },
  {
    id: "naturalistic-jobs-011",
    description: "networking hidden in career dread",
    message: "Career stuff makes me feel awkward because everyone says just network like it is normal. I guess the specific thing I need help with is informational interviews, because I don't know what I am supposed to ask.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Informational Interviews",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:jobs]",
  },
  {
    id: "naturalistic-jobs-012",
    description: "job offer confusion about negotiation",
    message: "I got a part-time job offer and I know that should be good news. But the pay and schedule part made me nervous, and I realized I don't understand salary negotiation at all.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Salary Negotiation",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:jobs]",
  },

  // ---------------------------------------------------------------------------
  // HEALTH
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-health-013",
    description: "nutrition label issue hidden in healthy eating context",
    message: "Why does a nutrition label say one number but then the serving size makes the whole thing feel like a trick? I am trying to eat healthier, but serving size is the part that keeps messing me up.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Serving Size",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:health]",
  },
  {
    id: "naturalistic-health-014",
    description: "sleep cycle target implicit in tiredness message",
    message: "Why do I wake up tired even when I technically slept enough hours? I keep saying I need more sleep, but I think sleep cycles are the thing I actually need to understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Sleep Cycles",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:health]",
  },
  {
    id: "naturalistic-health-015",
    description: "blood pressure message with systolic/diastolic comparison",
    message: "The nurse said my blood pressure numbers and I nodded because that seemed easier. But later I realized I don't know what systolic vs diastolic actually means.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Systolic vs Diastolic Blood Pressure",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:health]",
  },
  {
    id: "naturalistic-health-016",
    description: "immune response hidden under cold and flu confusion",
    message: "I get colds and I know my body fights them somehow. The actual thing I want to understand is the immune response, because the white blood cell stuff feels like a story with missing steps.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Immune Response",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:health]",
  },

  // ---------------------------------------------------------------------------
  // HISTORY
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-history-017",
    description: "history causation hidden in broad revolution message",
    message: "What actually caused the French Revolution if it was not just one angry crowd or one bad king? I can remember some names, but the cause-and-effect chain still feels mushy.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Causes of the French Revolution",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:history]",
  },
  {
    id: "naturalistic-history-018",
    description: "primary source analysis hidden in essay complaint",
    message: "How do I analyze a primary source instead of just summarizing what it says? My history essay feedback keeps saying analysis, and I do not think I actually know what that means.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Primary Source Analysis",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:history]",
  },
  {
    id: "naturalistic-history-019",
    description: "cold war proxy wars target implied",
    message: "The Cold War seems easy when it is just USA vs USSR. But then Korea and Vietnam show up and I stop understanding how proxy wars fit into the bigger picture.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Proxy Wars",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:history]",
  },
  {
    id: "naturalistic-history-020",
    description: "historical significance buried in test wording",
    message: "I knew the event but still got the short answer wrong. The wording asked why it mattered, so I think historical significance is the skill I am missing.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Historical Significance",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:history]",
  },

  // ---------------------------------------------------------------------------
  // CODING
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-coding-021",
    description: "async confusion hidden in code frustration",
    message: "Why does my JavaScript output happen in an order that makes no sense even though the lines look like they should run one after another? I keep blaming the function, but asynchronous code is probably the real issue.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Asynchronous Code",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:coding]",
  },
  {
    id: "naturalistic-coding-022",
    description: "React state update issue from UI bug",
    message: "When does React state actually update after I click a button? The UI changes in a way that feels delayed or fake, so I think React state updates are what I do not understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "React State Updates",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:coding]",
  },
  {
    id: "naturalistic-coding-023",
    description: "API error handling implied by fetch message",
    message: "I copied a fetch example and it worked until the server sent back something weird. The part I need is API error handling, not another basic fetch tutorial.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "API Error Handling",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:coding]",
  },
  {
    id: "naturalistic-coding-024",
    description: "recursion hidden in puzzle frustration",
    message: "I was doing a coding puzzle and I can solve the first level manually. But the answer keeps calling itself and I lose the thread, so recursion is probably the target.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Recursion",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:coding]",
  },

  // ---------------------------------------------------------------------------
  // GRAMMAR
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-grammar-025",
    description: "comma splice hidden in writing problem",
    message: "What is a comma splice if the sentence still sounds fine when I read it quickly? My teacher marked a few of them, and I think I keep making that mistake without noticing.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Comma Splices",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:grammar]",
  },
  {
    id: "naturalistic-grammar-026",
    description: "subject verb agreement buried in essay issue",
    message: "I know what my essay is trying to say, but some sentences sound wrong and I can't hear why. The actual issue might be subject-verb agreement.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Subject-Verb Agreement",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:grammar]",
  },
  {
    id: "naturalistic-grammar-027",
    description: "your vs you're comparison naturalistic",
    message: "This is embarrassing because I know I learned it before. But when I type quickly, your and you're still blur together, so I need to fix that comparison.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Your vs You're",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:grammar]",
  },
  {
    id: "naturalistic-grammar-028",
    description: "passive voice hidden in feedback",
    message: "How do I spot passive voice in my own writing when the sentence still sounds normal to me? My teacher wrote it in the margin, but I only understand the phrase in a vague way.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Passive Voice",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:grammar]",
  },

  // ---------------------------------------------------------------------------
  // SCHOOLWORK
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-schoolwork-029",
    description: "procrastination with task initiation target",
    message: "I keep saying I am lazy, but that feels too vague and also kind of mean. The problem is I can know the assignment matters and still not start, so task initiation is probably the thing.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Task Initiation",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:schoolwork]",
  },
  {
    id: "naturalistic-schoolwork-030",
    description: "study plan target hidden in overwhelmed message",
    message: "Where do I even start when all my notes are open and every subject feels urgent at the same time? It is not one class topic exactly; I need to understand study planning without panicking.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Study Planning",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:schoolwork]",
  },
  {
    id: "naturalistic-schoolwork-031",
    description: "test anxiety target but not the whole subject",
    message: "Why do I blank on tests even when I understood the homework the night before? The subject is not the only issue, because test anxiety is messing with what I can show.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Test Anxiety",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:schoolwork]",
  },
  {
    id: "naturalistic-schoolwork-032",
    description: "note taking issue implicit",
    message: "During lectures I write down random phrases and then later they look like clues from someone else's brain. I think the actual skill I need is note-taking structure.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Note-Taking Structure",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:schoolwork]",
  },

  // ---------------------------------------------------------------------------
  // MUSIC
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-music-033",
    description: "rhythm target hidden in piano frustration",
    message: "How do I know how long to hold notes when I can read the pitch but the timing falls apart? Piano is not the whole problem; rhythm notation is the thing I need.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Rhythm Notation",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:music]",
  },
  {
    id: "naturalistic-music-034",
    description: "secondary dominants buried in theory message",
    message: "Music theory was okay when chords stayed in one key. But secondary dominants make the whole page feel like it suddenly changed languages.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Secondary Dominants",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:music]",
  },
  {
    id: "naturalistic-music-035",
    description: "ear training implicit in singing issue",
    message: "I can sing along when someone else starts. But if I have to find the interval myself, I freeze, so the real target is interval recognition.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Interval Recognition",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:music]",
  },
  {
    id: "naturalistic-music-036",
    description: "circle of fifths hidden in memorization problem",
    message: "Why is the circle of fifths arranged in that order instead of just being a random memorization wheel? I memorized the picture, but I do not understand the logic behind it.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Circle of Fifths",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:music]",
  },

  // ---------------------------------------------------------------------------
  // GEOGRAPHY
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-geography-037",
    description: "map scale target hidden in map-reading complaint",
    message: "How do I use map scale to figure out distance instead of just guessing from how far apart two places look? I can read labels, but map scale is where I get lost.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Map Scale",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:geography]",
  },
  {
    id: "naturalistic-geography-038",
    description: "latitude longitude comparison",
    message: "Which one is latitude and which one is longitude when coordinates have directions after them? Geography seems simple until those two start blending together.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Latitude vs Longitude",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:geography]",
  },
  {
    id: "naturalistic-geography-039",
    description: "rain shadow effect implicit in mountains and climate",
    message: "We learned that one side of a mountain can be dry and the other side wetter. I can repeat that fact, but the rain shadow effect is the part I can't really explain.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Rain Shadow Effect",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:geography]",
  },
  {
    id: "naturalistic-geography-040",
    description: "plate boundaries target from earthquake message",
    message: "Earthquakes make sense in the dramatic movie version. But the worksheet asks about types of plate boundaries, and that is where I lose the logic.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Types of Plate Boundaries",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:geography]",
  },

  // ---------------------------------------------------------------------------
  // DRIVING
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-driving-041",
    description: "parallel parking buried in driving anxiety",
    message: "How do I parallel park without forgetting every step the second there is another car behind me? Driving itself is getting less scary, but parallel parking still makes the car feel huge.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Parallel Parking",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:driving]",
  },
  {
    id: "naturalistic-driving-042",
    description: "right of way implicit",
    message: "Who has the right of way at an intersection when everyone seems ready to move at once? I know how to steer and brake, but deciding whose turn it is makes me tense.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Right of Way",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:driving]",
  },
  {
    id: "naturalistic-driving-043",
    description: "merge lanes topic hidden in highway message",
    message: "Highway driving looks fine when someone else does it. But merge lanes make me panic because I don't know when I am supposed to speed up or wait.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Merge Lanes",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:driving]",
  },
  {
    id: "naturalistic-driving-044",
    description: "blind spot checking target",
    message: "My instructor keeps saying check your blind spot and I do it, but it feels performative. I need to understand blind spot checks in a real way, not just turn my head randomly.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Blind Spot Checks",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:driving]",
  },

  // ---------------------------------------------------------------------------
  // ART
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-art-045",
    description: "perspective target hidden in drawing problem",
    message: "Why does my room drawing tilt weirdly once I add walls or a street, even though each line looks fine by itself? I think one-point perspective is the actual thing I need.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "One-Point Perspective",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:art]",
  },
  {
    id: "naturalistic-art-046",
    description: "color theory implied in painting issue",
    message: "I mixed paint for a sunset and somehow made mud. The picture in my head was bright, but color mixing is the part I don't understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Color Mixing",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:art]",
  },
  {
    id: "naturalistic-art-047",
    description: "negative space hidden in sketching feedback",
    message: "What am I supposed to look at when an art teacher says draw the space around the object? I nodded like it made sense, but negative space is what I need help seeing.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Negative Space",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:art]",
  },
  {
    id: "naturalistic-art-048",
    description: "shading target from flat drawing",
    message: "My apple drawing looks like a sticker instead of something round. The outline is not the problem, shading values are.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Shading Values",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:art]",
  },

  // ---------------------------------------------------------------------------
  // POLITICS CLASS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-politics_class-049",
    description: "separation of powers hidden in civics message",
    message: "Who can actually stop whom in government when civics class talks about branches checking each other? I can memorize the words separately, but separation of powers is where I get lost.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Separation of Powers",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:politics_class]",
  },
  {
    id: "naturalistic-politics_class-050",
    description: "federalism target implied by levels of government",
    message: "Where does federal power end and provincial or state power begin when both levels of government seem involved? The worksheet makes it sound obvious, but federalism is the part I need.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Federalism",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:politics_class]",
  },
  {
    id: "naturalistic-politics_class-051",
    description: "electoral college as class concept not current politics",
    message: "This is for politics class, not like a debate thing. I can follow the popular vote idea, but the electoral college is the part that stops making sense.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Electoral College",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:politics_class]",
  },
  {
    id: "naturalistic-politics_class-052",
    description: "civil liberties vs civil rights comparison",
    message: "The chapter uses civil liberties and civil rights like I should just feel the difference. I don't, so I need the comparison more than a huge politics overview.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Civil Liberties vs Civil Rights",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:politics_class]",
  },

  // ---------------------------------------------------------------------------
  // BIOLOGY
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-biology-053",
    description: "osmosis target hidden in cell transport",
    message: "Why is osmosis about water specifically when cell transport also talks about other things moving across membranes? I keep mixing the movement stories together.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Osmosis",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:biology]",
  },
  {
    id: "naturalistic-biology-054",
    description: "natural selection implied by evolution wording",
    message: "How does natural selection actually work without just saying animals adapt because they need to? Evolution makes sense as a big idea, but that explanation feels wrong.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Natural Selection",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:biology]",
  },
  {
    id: "naturalistic-biology-055",
    description: "mitosis meiosis comparison",
    message: "I know both mitosis and meiosis are cell division, which is exactly the problem. They blur together in my head, so I need that comparison.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Mitosis vs Meiosis",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:biology]",
  },
  {
    id: "naturalistic-biology-056",
    description: "enzyme activation energy target",
    message: "The enzyme lesson felt okay until the graph showed activation energy. I can say enzymes speed things up, but I don't know what happens to the energy barrier.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Activation Energy",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:biology]",
  },

  // ---------------------------------------------------------------------------
  // CHEMISTRY
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-chemistry-057",
    description: "mole concept hidden in stoichiometry dread",
    message: "What is a mole in chemistry supposed to represent when the problem turns into a unit-conversion maze? I keep blaming stoichiometry, but the mole concept is probably the thing I never got.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Mole Concept",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:chemistry]",
  },
  {
    id: "naturalistic-chemistry-058",
    description: "balancing equations implicit",
    message: "I can read a chemical equation when it is already finished. But when I have to balance it myself, I start changing numbers randomly.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Balancing Chemical Equations",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:chemistry]",
  },
  {
    id: "naturalistic-chemistry-059",
    description: "electronegativity vs ionization energy comparison",
    message: "The periodic trends lesson has too many arrows. Electronegativity and ionization energy keep feeling like the same idea even though I know they are not.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Electronegativity vs Ionization Energy",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:chemistry]",
  },
  {
    id: "naturalistic-chemistry-060",
    description: "pH target hidden in acid base message",
    message: "Why does the pH number go down when something is more acidic? Acids and bases were okay with simple examples, but pH is where the numbers feel backwards.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "pH",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:chemistry]",
  },

  // ---------------------------------------------------------------------------
  // FINANCE
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-finance-061",
    description: "compound interest implicit in bank app anxiety",
    message: "How does compound interest make a savings number change faster than I expect? The bank calculator looked simple, but I could not predict what it was doing.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Compound Interest",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:finance]",
  },
  {
    id: "naturalistic-finance-062",
    description: "APR target hidden in credit card message",
    message: "What does APR actually mean on a credit card if I already know interest is bad when I carry a balance? The term feels like something I was supposed to learn in an adult class.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "APR",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:finance]",
  },
  {
    id: "naturalistic-finance-063",
    description: "budgeting comparison needs fixed vs variable expenses",
    message: "My budget looks fine until real life happens. I think I am mixing up fixed and variable expenses, because some costs keep surprising me even though I should have planned them.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Fixed vs Variable Expenses",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:finance]",
  },
  {
    id: "naturalistic-finance-064",
    description: "index funds hidden in investing message",
    message: "Investing advice keeps saying be diversified and don't pick random stocks. I think index funds are the thing I need explained, because everyone uses the phrase like it is self-evident.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Index Funds",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:finance]",
  },

  // ---------------------------------------------------------------------------
  // CARS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-cars-065",
    description: "torque vs horsepower comparison",
    message: "What is the difference between torque and horsepower if both seem to mean the car is powerful? Car videos throw them around like they are obvious, but they blur together for me.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Torque vs Horsepower",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cars]",
  },
  {
    id: "naturalistic-cars-066",
    description: "transmission topic hidden in driving feel",
    message: "I know the engine makes the car move, roughly. But the way gears change still feels mysterious, so I think automatic transmission is the actual topic.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Automatic Transmission",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cars]",
  },
  {
    id: "naturalistic-cars-067",
    description: "ABS braking target",
    message: "The dashboard light said ABS and I pretended I knew what that meant. I understand braking in general, but anti-lock braking system is the part I need.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Anti-Lock Braking System",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cars]",
  },
  {
    id: "naturalistic-cars-068",
    description: "oil change interval implicit",
    message: "When should I actually change my oil if one place says months and another says kilometers? I get that oil changes matter, but oil change intervals make me second-guess everything.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Oil Change Intervals",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:cars]",
  },

  // ---------------------------------------------------------------------------
  // NATURE
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-nature-069",
    description: "photosynthesis target but hidden in plant message",
    message: "How do plants actually make food in photosynthesis when the diagram starts moving arrows everywhere? I understand the simple slogan, but not the process.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Photosynthesis",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:nature]",
  },
  {
    id: "naturalistic-nature-070",
    description: "food web vs food chain comparison",
    message: "What is the difference between a food chain and a food web when both are showing who eats what? I can follow a straight line, but food webs make me lose the direction.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Food Chains vs Food Webs",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:nature]",
  },
  {
    id: "naturalistic-nature-071",
    description: "pollination target implicit",
    message: "Flowers make sense visually, but the reproduction part is weirdly hard to picture. Pollination is the thing I can define but not really explain.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Pollination",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:nature]",
  },
  {
    id: "naturalistic-nature-072",
    description: "ecosystem succession hidden in forest recovery",
    message: "We learned that forests can regrow after fires. I can remember the examples, but ecological succession is the process I don't actually understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Ecological Succession",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:nature]",
  },

  // ---------------------------------------------------------------------------
  // PLUMBING
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-plumbing-073",
    description: "P-trap target hidden in sink smell",
    message: "Why does every article about sink smell mention the P-trap like I should know what it does? The sink is not broken in an obvious way, but that part seems important.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "P-Trap",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:plumbing]",
  },
  {
    id: "naturalistic-plumbing-074",
    description: "water pressure target",
    message: "What affects water pressure when the shower technically works but feels weak? I keep reading about valves and pipe size, but I do not know which part matters.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Water Pressure",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:plumbing]",
  },
  {
    id: "naturalistic-plumbing-075",
    description: "shutoff valve target implied",
    message: "I am not trying to become a plumber. I just want to know where the shutoff valve fits into the whole leak situation before I panic.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Shutoff Valve",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:plumbing]",
  },
  {
    id: "naturalistic-plumbing-076",
    description: "vent pipe target hidden in drainage problem",
    message: "The drain gurgles and I thought that just meant a clog. But the explanation mentioned air and vents, so plumbing vent pipes are what I don't understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Plumbing Vent Pipes",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:plumbing]",
  },

  // ---------------------------------------------------------------------------
  // SPACE
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-space-077",
    description: "orbital velocity hidden in orbit question",
    message: "How can something stay in orbit if it is supposedly falling around Earth the whole time? I sort of get the phrase, but orbital velocity is where it stops feeling intuitive.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Orbital Velocity",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:space]",
  },
  {
    id: "naturalistic-space-078",
    description: "moon phases target",
    message: "Why does the Moon look like it changes shape if it is not actually changing shape? I know the words, but moon phases still confuse me because I cannot picture the positions.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Moon Phases",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:space]",
  },
  {
    id: "naturalistic-space-079",
    description: "gravity vs weight comparison",
    message: "I can say gravity pulls things down, but then space class starts talking about mass and weight. I think gravity vs weight is the comparison I need.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Gravity vs Weight",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:space]",
  },
  {
    id: "naturalistic-space-080",
    description: "redshift target implicit",
    message: "The universe expanding sounds amazing until the teacher says light stretches. I think redshift is the part where I lose the mechanism.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Redshift",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:space]",
  },

  // ---------------------------------------------------------------------------
  // LAW
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-law-081",
    description: "burden of proof target",
    message: "Who has to prove something in a law case, and why does that change depending on the type of case? The phrase burden of proof keeps showing up and I keep missing the logic.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Burden of Proof",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:law]",
  },
  {
    id: "naturalistic-law-082",
    description: "civil vs criminal comparison",
    message: "I keep hearing civil case and criminal case and I know they are not the same. But the difference still feels slippery, so I need civil law vs criminal law.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Civil Law vs Criminal Law",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:law]",
  },
  {
    id: "naturalistic-law-083",
    description: "precedent target in legal reasoning",
    message: "The reading keeps saying the judge followed precedent and I kind of get the vibe. But legal precedent is the part I cannot explain without sounding circular.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Legal Precedent",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:law]",
  },
  {
    id: "naturalistic-law-084",
    description: "contract consideration hidden in agreement message",
    message: "What makes a promise legally count as a contract when the textbook says consideration is required? I thought contracts were just promises written down, but that is clearly too simple.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Consideration in Contracts",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:law]",
  },

  // ---------------------------------------------------------------------------
  // EMOTIONS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-emotions-085",
    description: "emotion regulation target hidden in feeling message",
    message: "How do people regulate an emotion without just arguing with it in their head until it gets louder? I get overwhelmed and I think emotion regulation is the thing I want to understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Emotion Regulation",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:emotions]",
  },
  {
    id: "naturalistic-emotions-086",
    description: "rumination target implicit",
    message: "Why do I keep replaying conversations when I already know nothing useful is happening? It is not exactly problem solving, so I think rumination is the thing I need help naming.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Rumination",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:emotions]",
  },
  {
    id: "naturalistic-emotions-087",
    description: "cognitive reappraisal hidden in advice confusion",
    message: "People say just look at it differently and that sounds fake to me. But maybe cognitive reappraisal is the real skill I do not understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Cognitive Reappraisal",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:emotions]",
  },
  {
    id: "naturalistic-emotions-088",
    description: "null emotional no topic",
    message: "I feel weird and tired and kind of behind, but I cannot tell what the actual topic is. There is no specific class thing or concept in my head yet.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: null,
    expectedResolutionKind: "no_match",
    expectedShouldCreate: false,
    notes: "[category:emotions]",
  },

  // ---------------------------------------------------------------------------
  // CONFUSION
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-confusion-089",
    description: "null pure confusion should stay null",
    message: "I do not even know what I am confused about. I opened the page and got that blank feeling, but no particular word or idea is standing out.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: null,
    expectedResolutionKind: "no_match",
    expectedShouldCreate: false,
    notes: "[category:confusion]",
  },
  {
    id: "naturalistic-confusion-090",
    description: "metacognitive confusion target",
    message: "How can I tell whether I understand something while I am answering instead of only after someone corrects me? I think the thing I need is monitoring my own understanding.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Monitoring Understanding",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:confusion]",
  },
  {
    id: "naturalistic-confusion-091",
    description: "concept map target hidden in scattered feeling",
    message: "Where do I start when every idea feels connected to every other idea in a bad way? I think concept mapping is what I need because I cannot see which idea depends on which.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Concept Mapping",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:confusion]",
  },
  {
    id: "naturalistic-confusion-092",
    description: "null vague help with no durable target",
    message: "Can you help me maybe. I know that is not a useful question, but my brain is just saying no and I do not have an actual topic yet.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: null,
    expectedResolutionKind: "no_match",
    expectedShouldCreate: false,
    notes: "[category:confusion]",
  },

  // ---------------------------------------------------------------------------
  // COMPARISONS
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-comparisons-093",
    description: "affect vs effect comparison",
    message: "When do I use affect and when do I use effect if I know the rule for two seconds and then forget it while writing? They still collapse into the same word in my head.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Affect vs Effect",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:comparisons]",
  },
  {
    id: "naturalistic-comparisons-094",
    description: "mean vs median comparison",
    message: "Why does one huge number change the mean so much but not the median in the same way? The stats examples are fine until mean and median stop feeling different.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Mean vs Median",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:comparisons]",
  },
  {
    id: "naturalistic-comparisons-095",
    description: "weather vs climate comparison",
    message: "What makes something weather instead of climate when the example still talks about temperature or rain? I can repeat the definition, but I cannot classify examples reliably.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Weather vs Climate",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:comparisons]",
  },
  {
    id: "naturalistic-comparisons-096",
    description: "sympathy vs empathy comparison",
    message: "I hear sympathy and empathy used like they are interchangeable. I know people say they are different, but I need the actual difference in a way that sticks.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Sympathy vs Empathy",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:comparisons]",
  },

  // ---------------------------------------------------------------------------
  // MIXED
  // ---------------------------------------------------------------------------
  {
    id: "naturalistic-mixed-097",
    description: "cooking chemistry crossover but true target is Maillard reaction",
    message: "Why is browning food not just the same thing as slowly burning it? I was cooking onions and someone mentioned the Maillard reaction, which seems to be the process I do not understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Maillard Reaction",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:mixed]",
  },
  {
    id: "naturalistic-mixed-098",
    description: "driving finance crossover but true target is depreciation",
    message: "I was looking at used cars and the prices made no sense to me. It is not really engines or loans this time, it is depreciation that I need to understand.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Depreciation",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:mixed]",
  },
  {
    id: "naturalistic-mixed-099",
    description: "art history comparison target",
    message: "In art history I can memorize the names, but Baroque and Renaissance still blur together when I look at a painting. I need the comparison, not just dates.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "Baroque vs Renaissance Art",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:mixed]",
  },
  {
    id: "naturalistic-mixed-100",
    description: "biology chemistry crossover but true target is pH scale",
    message: "The teacher talked about enzymes and acids in the same lesson, and I followed maybe half of it. But the pH scale is the number thing that keeps feeling backwards.",
    existingTopics: [],
    activeTopicId: null,
    expectedLabel: "pH Scale",
    expectedResolutionKind: "created_new_candidate",
    expectedShouldCreate: true,
    notes: "[category:mixed]",
  },
];
