export type KnownBundleLicenseKind = "cc0" | "cc_by" | "cc_by_4_0";

export type KnownBundleAssetMetadata = {
  file_name: string;
  source_title: string;
  creator_name: string;
  license_kind: KnownBundleLicenseKind;
  source_provider: string;
  source_url: string;
  source_asset_id: string;
  bundle_title: string;
  bundle_source_url: string;
};

const OFFICE_PACK_URL = "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9";
const OFFICE_PACK = new Map<string, KnownBundleAssetMetadata>([
  ["Adjustable Desk.glb", {"file_name": "Adjustable Desk.glb", "source_title": "Adjustable Desk", "creator_name": "jeff cobesign", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Adjustable Desk.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Air Vent.glb", {"file_name": "Air Vent.glb", "source_title": "Air Vent", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Air Vent.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Analog clock.glb", {"file_name": "Analog clock.glb", "source_title": "Analog clock", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Analog clock.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Bathroom Sink.glb", {"file_name": "Bathroom Sink.glb", "source_title": "Bathroom Sink", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Bathroom Sink.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Bathroom Toilet Paper.glb", {"file_name": "Bathroom Toilet Paper.glb", "source_title": "Bathroom Toilet Paper", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Bathroom Toilet Paper.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Binder.glb", {"file_name": "Binder.glb", "source_title": "Binder", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Binder.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Bins.glb", {"file_name": "Bins.glb", "source_title": "Bins", "creator_name": "Dilan Shah", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Bins.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Blank Picture Frame.glb", {"file_name": "Blank Picture Frame.glb", "source_title": "Blank Picture Frame", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Blank Picture Frame.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Book Stack.glb", {"file_name": "Book Stack.glb", "source_title": "Book Stack", "creator_name": "Danni Bittman", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Book Stack.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Briefcase.glb", {"file_name": "Briefcase.glb", "source_title": "Briefcase", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Briefcase.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["CCTV Camera.glb", {"file_name": "CCTV Camera.glb", "source_title": "CCTV Camera", "creator_name": "Jörg H.", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:CCTV Camera.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cabinet Bed Drawer Tabl.glb", {"file_name": "Cabinet Bed Drawer Tabl.glb", "source_title": "Cabinet Bed Drawer Tabl", "creator_name": "Kenney", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cabinet Bed Drawer Tabl.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cabinet.glb", {"file_name": "Cabinet.glb", "source_title": "Cabinet", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cabinet.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Calendar-8GqQAqxi3qk.glb", {"file_name": "Calendar-8GqQAqxi3qk.glb", "source_title": "Calendar", "creator_name": "Tomáš Bayer", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/8GqQAqxi3qk", "source_asset_id": "8GqQAqxi3qk", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Calendar.glb", {"file_name": "Calendar.glb", "source_title": "Calendar", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Calendar.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cardboard Box.glb", {"file_name": "Cardboard Box.glb", "source_title": "Cardboard Box", "creator_name": "Nick Slough", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cardboard Box.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cardboard Boxes-pMdXdrUHvX.glb", {"file_name": "Cardboard Boxes-pMdXdrUHvX.glb", "source_title": "Cardboard Boxes", "creator_name": "Nick Slough", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/pMdXdrUHvX", "source_asset_id": "pMdXdrUHvX", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cardboard Boxes.glb", {"file_name": "Cardboard Boxes.glb", "source_title": "Cardboard Boxes", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cardboard Boxes.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Ceiling Fan.glb", {"file_name": "Ceiling Fan.glb", "source_title": "Ceiling Fan", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Ceiling Fan.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Ceiling Light.glb", {"file_name": "Ceiling Light.glb", "source_title": "Ceiling Light", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Ceiling Light.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Chair-1MFMOaz3zqe.glb", {"file_name": "Chair-1MFMOaz3zqe.glb", "source_title": "Chair", "creator_name": "CMHT Oculus", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/1MFMOaz3zqe", "source_asset_id": "1MFMOaz3zqe", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Chair.glb", {"file_name": "Chair.glb", "source_title": "Chair", "creator_name": "CMHT Oculus", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Chair.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Coat rack.glb", {"file_name": "Coat rack.glb", "source_title": "Coat rack", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Coat rack.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Coffee Table.glb", {"file_name": "Coffee Table.glb", "source_title": "Coffee Table", "creator_name": "Francisco Hui", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Coffee Table.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Coffee cup.glb", {"file_name": "Coffee cup.glb", "source_title": "Coffee cup", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Coffee cup.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Computer Screen.glb", {"file_name": "Computer Screen.glb", "source_title": "Computer Screen", "creator_name": "Kenney", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Computer Screen.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Computer mouse.glb", {"file_name": "Computer mouse.glb", "source_title": "Computer mouse", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Computer mouse.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Computer.glb", {"file_name": "Computer.glb", "source_title": "Computer", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Computer.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Couch Medium.glb", {"file_name": "Couch Medium.glb", "source_title": "Couch Medium", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Couch Medium.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Couch Small-ZOPP3KzNIk.glb", {"file_name": "Couch Small-ZOPP3KzNIk.glb", "source_title": "Couch Small", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/ZOPP3KzNIk", "source_asset_id": "ZOPP3KzNIk", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Couch Small.glb", {"file_name": "Couch Small.glb", "source_title": "Couch Small", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Couch Small.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Couch | Wide.glb", {"file_name": "Couch | Wide.glb", "source_title": "Couch | Wide", "creator_name": "Danni Bittman", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Couch | Wide.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Crushed Soda Can.glb", {"file_name": "Crushed Soda Can.glb", "source_title": "Crushed Soda Can", "creator_name": "Thermo_DynAmics", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Crushed Soda Can.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cup.glb", {"file_name": "Cup.glb", "source_title": "Cup", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cup.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Curtains Double.glb", {"file_name": "Curtains Double.glb", "source_title": "Curtains Double", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Curtains Double.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Cushions.glb", {"file_name": "Cushions.glb", "source_title": "Cushions", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Cushions.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Dartboard.glb", {"file_name": "Dartboard.glb", "source_title": "Dartboard", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Dartboard.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Darts.glb", {"file_name": "Darts.glb", "source_title": "Darts", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Darts.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk Toy.glb", {"file_name": "Desk Toy.glb", "source_title": "Desk Toy", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Desk Toy.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk-7ban171PzCS.glb", {"file_name": "Desk-7ban171PzCS.glb", "source_title": "Desk", "creator_name": "CMHT Oculus", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/7ban171PzCS", "source_asset_id": "7ban171PzCS", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk-EtJlOllzbf.glb", {"file_name": "Desk-EtJlOllzbf.glb", "source_title": "Desk", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/EtJlOllzbf", "source_asset_id": "EtJlOllzbf", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk-ISpMh81QGq.glb", {"file_name": "Desk-ISpMh81QGq.glb", "source_title": "Desk", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/ISpMh81QGq", "source_asset_id": "ISpMh81QGq", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk-V86Go2rlnq.glb", {"file_name": "Desk-V86Go2rlnq.glb", "source_title": "Desk", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/V86Go2rlnq", "source_asset_id": "V86Go2rlnq", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Desk.glb", {"file_name": "Desk.glb", "source_title": "Desk", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Desk.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Doorway Front.glb", {"file_name": "Doorway Front.glb", "source_title": "Doorway Front", "creator_name": "Kenney", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Doorway Front.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Doorway.glb", {"file_name": "Doorway.glb", "source_title": "Doorway", "creator_name": "Kenney", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Doorway.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Dual Monitors on sit-stand arm.glb", {"file_name": "Dual Monitors on sit-stand arm.glb", "source_title": "Dual Monitors on sit-stand arm", "creator_name": "involuntary tsetse", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Dual Monitors on sit-stand arm.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Electrical outlet.glb", {"file_name": "Electrical outlet.glb", "source_title": "Electrical outlet", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Electrical outlet.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["File Cabinet.glb", {"file_name": "File Cabinet.glb", "source_title": "File Cabinet", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:File Cabinet.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Fire Exit Sign-0ywPpb36cyK.glb", {"file_name": "Fire Exit Sign-0ywPpb36cyK.glb", "source_title": "Fire Exit Sign", "creator_name": "Thomas Oldham", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/0ywPpb36cyK", "source_asset_id": "0ywPpb36cyK", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Fire Exit Sign.glb", {"file_name": "Fire Exit Sign.glb", "source_title": "Fire Exit Sign", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Fire Exit Sign.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Fire Extinguisher.glb", {"file_name": "Fire Extinguisher.glb", "source_title": "Fire Extinguisher", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Fire Extinguisher.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Houseplant-VtJh4Irl4w.glb", {"file_name": "Houseplant-VtJh4Irl4w.glb", "source_title": "Houseplant", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/VtJh4Irl4w", "source_asset_id": "VtJh4Irl4w", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Houseplant-bfLOqIV5uP.glb", {"file_name": "Houseplant-bfLOqIV5uP.glb", "source_title": "Houseplant", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/bfLOqIV5uP", "source_asset_id": "bfLOqIV5uP", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Houseplant-e9oRt-Ct6js.glb", {"file_name": "Houseplant-e9oRt-Ct6js.glb", "source_title": "Houseplant", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/e9oRt-Ct6js", "source_asset_id": "e9oRt-Ct6js", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Houseplant.glb", {"file_name": "Houseplant.glb", "source_title": "Houseplant", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Houseplant.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Keyboard-fOy2zvPJAj-.glb", {"file_name": "Keyboard-fOy2zvPJAj-.glb", "source_title": "Keyboard", "creator_name": "Alex Safayan", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/fOy2zvPJAj-", "source_asset_id": "fOy2zvPJAj-", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Keyboard.glb", {"file_name": "Keyboard.glb", "source_title": "Keyboard", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Keyboard.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Ladder.glb", {"file_name": "Ladder.glb", "source_title": "Ladder", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Ladder.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Lamp.glb", {"file_name": "Lamp.glb", "source_title": "Lamp", "creator_name": "burunduk", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Lamp.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Laptop bag.glb", {"file_name": "Laptop bag.glb", "source_title": "Laptop bag", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Laptop bag.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Light Cube.glb", {"file_name": "Light Cube.glb", "source_title": "Light Cube", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Light Cube.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Light Desk.glb", {"file_name": "Light Desk.glb", "source_title": "Light Desk", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Light Desk.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Light Floor.glb", {"file_name": "Light Floor.glb", "source_title": "Light Floor", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Light Floor.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Light Icosahedron.glb", {"file_name": "Light Icosahedron.glb", "source_title": "Light Icosahedron", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Light Icosahedron.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Light Switch.glb", {"file_name": "Light Switch.glb", "source_title": "Light Switch", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Light Switch.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["MS Gundam RX-78-2 with weapons.glb", {"file_name": "MS Gundam RX-78-2 with weapons.glb", "source_title": "MS Gundam RX-78-2 with weapons", "creator_name": "Tipatat Chennavasin", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:MS Gundam RX-78-2 with weapons.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Magazine.glb", {"file_name": "Magazine.glb", "source_title": "Magazine", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Magazine.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Manhole cover.glb", {"file_name": "Manhole cover.glb", "source_title": "Manhole cover", "creator_name": "Zsky", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Manhole cover.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Medium Book Shelf.glb", {"file_name": "Medium Book Shelf.glb", "source_title": "Medium Book Shelf", "creator_name": "Zsky", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Medium Book Shelf.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Message board.glb", {"file_name": "Message board.glb", "source_title": "Message board", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Message board.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Monitor.glb", {"file_name": "Monitor.glb", "source_title": "Monitor", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Monitor.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Mouse.glb", {"file_name": "Mouse.glb", "source_title": "Computer Mouse", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Mouse.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Mousepad.glb", {"file_name": "Mousepad.glb", "source_title": "Mousepad", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Mousepad.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Mug With Office Tool.glb", {"file_name": "Mug With Office Tool.glb", "source_title": "Mug With Office Tool", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Mug With Office Tool.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Mug.glb", {"file_name": "Mug.glb", "source_title": "Mug", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Mug.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Night Stand.glb", {"file_name": "Night Stand.glb", "source_title": "Night Stand", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Night Stand.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Notebook.glb", {"file_name": "Notebook.glb", "source_title": "Notebook", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Notebook.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Office Chair.glb", {"file_name": "Office Chair.glb", "source_title": "Office Chair", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Office Chair.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Office Phone.glb", {"file_name": "Office Phone.glb", "source_title": "Office Phone", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Office Phone.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Pens.glb", {"file_name": "Pens.glb", "source_title": "Pens", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Pens.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Phone-1L9oJAw6nY2.glb", {"file_name": "Phone-1L9oJAw6nY2.glb", "source_title": "Phone", "creator_name": "Alex Safayan", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/1L9oJAw6nY2", "source_asset_id": "1L9oJAw6nY2", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Phone.glb", {"file_name": "Phone.glb", "source_title": "Phone", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Phone.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Plant - White Pot.glb", {"file_name": "Plant - White Pot.glb", "source_title": "Plant - White Pot", "creator_name": "Jakers_H", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Plant - White Pot.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Polaroids.glb", {"file_name": "Polaroids.glb", "source_title": "Polaroids", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Polaroids.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Potted Plant.glb", {"file_name": "Potted Plant.glb", "source_title": "Potted Plant", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Potted Plant.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Printer.glb", {"file_name": "Printer.glb", "source_title": "Printer", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Printer.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Rubik's cube.glb", {"file_name": "Rubik's cube.glb", "source_title": "Rubik's cube", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Rubik's cube.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Rug Round.glb", {"file_name": "Rug Round.glb", "source_title": "Rug Round", "creator_name": "Kenney", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Rug Round.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Rug.glb", {"file_name": "Rug.glb", "source_title": "Rug", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Rug.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Shelf Small.glb", {"file_name": "Shelf Small.glb", "source_title": "Shelf Small", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Shelf Small.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Shelf.glb", {"file_name": "Shelf.glb", "source_title": "Shelf", "creator_name": "Julien Kleber (Juliusprod)", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Shelf.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Skateboard.glb", {"file_name": "Skateboard.glb", "source_title": "Skateboard", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Skateboard.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Small Stack of Paper.glb", {"file_name": "Small Stack of Paper.glb", "source_title": "Small Stack of Paper", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Small Stack of Paper.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Soda Can.glb", {"file_name": "Soda Can.glb", "source_title": "Soda Can", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Soda Can.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Soda.glb", {"file_name": "Soda.glb", "source_title": "Soda", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Soda.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Standing Desk.glb", {"file_name": "Standing Desk.glb", "source_title": "Standing Desk", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Standing Desk.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Stapler.glb", {"file_name": "Stapler.glb", "source_title": "Stapler", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Stapler.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Sticky Notes.glb", {"file_name": "Sticky Notes.glb", "source_title": "Sticky Notes", "creator_name": "Nick Slough", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Sticky Notes.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Sticky notes.glb", {"file_name": "Sticky notes.glb", "source_title": "Sticky notes", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Sticky notes.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Table Large Circular.glb", {"file_name": "Table Large Circular.glb", "source_title": "Table Large Circular", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Table Large Circular.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Table Tennis Paddle.glb", {"file_name": "Table Tennis Paddle.glb", "source_title": "Table Tennis Paddle", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Table Tennis Paddle.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Table tennis table.glb", {"file_name": "Table tennis table.glb", "source_title": "Table tennis table", "creator_name": "Poly by Google", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Table tennis table.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Table.glb", {"file_name": "Table.glb", "source_title": "Table", "creator_name": "Darwin Yamamoto", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Table.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Tissue Box.glb", {"file_name": "Tissue Box.glb", "source_title": "Tissue Box", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Tissue Box.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Toilet Paper stack.glb", {"file_name": "Toilet Paper stack.glb", "source_title": "Toilet Paper stack", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Toilet Paper stack.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Toilet.glb", {"file_name": "Toilet.glb", "source_title": "Toilet", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Toilet.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Towel Rack.glb", {"file_name": "Towel Rack.glb", "source_title": "Towel Rack", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Towel Rack.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Trash Bin.glb", {"file_name": "Trash Bin.glb", "source_title": "Trash Bin", "creator_name": "CreativeTrio", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Trash Bin.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Trashcan Small.glb", {"file_name": "Trashcan Small.glb", "source_title": "Trashcan Small", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Trashcan Small.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Trashcan.glb", {"file_name": "Trashcan.glb", "source_title": "Trashcan", "creator_name": "Quaternius", "license_kind": "cc0", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Trashcan.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Trophy.glb", {"file_name": "Trophy.glb", "source_title": "Trophy", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Trophy.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Various Stacks of Paper.glb", {"file_name": "Various Stacks of Paper.glb", "source_title": "Various Stacks of Paper", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Various Stacks of Paper.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Vending Machine.glb", {"file_name": "Vending Machine.glb", "source_title": "Vending Machine", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Vending Machine.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Art 02.glb", {"file_name": "Wall Art 02.glb", "source_title": "Wall Art 02", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Wall Art 02.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Art 03.glb", {"file_name": "Wall Art 03.glb", "source_title": "Wall Art 03", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Wall Art 03.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Art 05.glb", {"file_name": "Wall Art 05.glb", "source_title": "Wall Art 05", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Wall Art 05.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Art 06-1U5roiXQZAM.glb", {"file_name": "Wall Art 06-1U5roiXQZAM.glb", "source_title": "Wall Art 06", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/m/1U5roiXQZAM", "source_asset_id": "1U5roiXQZAM", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Art 06.glb", {"file_name": "Wall Art 06.glb", "source_title": "Wall Art 06", "creator_name": "Jarlan Perez", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Wall Art 06.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Wall Shelf.glb", {"file_name": "Wall Shelf.glb", "source_title": "Wall Shelf", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Wall Shelf.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Water Cooler.glb", {"file_name": "Water Cooler.glb", "source_title": "Water Cooler", "creator_name": "J-Toastie", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Water Cooler.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Webcam.glb", {"file_name": "Webcam.glb", "source_title": "Webcam", "creator_name": "dook", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Webcam.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Whiteboard.glb", {"file_name": "Whiteboard.glb", "source_title": "Whiteboard", "creator_name": "jeremy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Whiteboard.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["Window Blinds.glb", {"file_name": "Window Blinds.glb", "source_title": "Window Blinds", "creator_name": "Alex Safayan", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:Window Blinds.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
  ["clipboard.glb", {"file_name": "clipboard.glb", "source_title": "clipboard", "creator_name": "William Murphy", "license_kind": "cc_by", "source_provider": "Poly Pizza", "source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9", "source_asset_id": "UGIy7YcQP9:clipboard.glb", "bundle_title": "The Office Pack", "bundle_source_url": "https://poly.pizza/bundle/The-Office-Pack-UGIy7YcQP9"}],
]);

export function identifyKnownBundle(fileName: string, memberNames: string[]) {
  const normalized = fileName.trim().toLowerCase();
  const names = new Set(memberNames.map((value) => value.replace(/^.*[\\/]/, "")));
  const officeMarkers = ["Adjustable Desk.glb", "Office Phone.glb", "Vending Machine.glb", "Whiteboard.glb"];
  const officeLike = normalized.includes("office pack") && memberNames.length === 125 && officeMarkers.every((name) => names.has(name));
  if (officeLike) return { id: "poly_pizza_office_pack_UGIy7YcQP9", title: "The Office Pack", source_url: OFFICE_PACK_URL };
  return null;
}

export function metadataForKnownBundleMember(bundleId: string | null | undefined, memberPath: string) {
  if (bundleId !== "poly_pizza_office_pack_UGIy7YcQP9") return null;
  const fileName = memberPath.replace(/^.*[\\/]/, "");
  return OFFICE_PACK.get(fileName) ?? null;
}
